#[font]
#normal = { family = "JetBrainsMono NFP", style = "Regular" }
#size = 8
#
#[colors.primary]
#background            = "#1E1E2E"
#foreground            = "#ff0000"

# https://github.com/Filip-Nachov/dotfiles/blob/main/.config/alacritty/alacritty.toml

#[colors.cursor]
#cursor = "#fbf1c7"
#text = "#fe8019"
#
#[colors.normal]
#black = "#928374"
#blue = "#83a598"
#cyan = "#8ec07c"
#green = "#ff00ff"
#magenta = "#d3896b"
#red = "#fb4934"
#white = "#928374"
#yellow = "#fadb2f"
#
[colors.primary]
#foreground = "#ff0000"

#
[font]
size = 10
#
[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Medium"

[colors]
transparent_background_colors = true

[window]
decorations = "Transparent"
dynamic_title = true
padding = { x = 5, y = 5}

opacity = 0.5
#startup_mode = "Maximized"
